kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-3par
  annotations:
    volume.beta.kubernetes.io/storage-class: 3par
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
