#!/usr/bin/env bash
SCRIPT_ROOT=$( cd `dirname $0`; pwd)
echo "Read description in the $SCRIPT_ROOT/README.md"
read -p "Input [CLIENT]: " CLIENT
read -p "Input [JUMPBOX_IP]: " JUMPBOX_IP
read -p "Input [POC_DOMAIN]: " POC_DOMAIN

cat <<EOF  > $SCRIPT_ROOT/.env
CLIENT=$CLIENT
JUMPBOX_IP=$JUMPBOX_IP
POC_DOMAIN=$POC_DOMAIN
ROOT_DOMAIN=${CLIENT}.${POC_DOMAIN}
LOCAL_REGISTRY=$JUMPBOX_IP:5000
TKG_CUSTOM_IMAGE_REPOSITORY=$JUMPBOX_IP:5000
TKG_CUSTOM_IMAGE_REPOSITORY_SKIP_TLS_VERIFY=true

EOF


