apiVersion: v1
data:
  secretkey: RFR1OTRwaDR6ZFlFbUxVZ1FNanBDVGMwaGdxdlY2QXptRHIvejZEbjhlK2dacDN3c1l0SUhQSnloWHZoTmVBVApoSVFtUzM2bkd5Uk10SzhlaHdWMWtzZ3F0b1FNVlI5bStmK2VuRGozbGt1dTVnZktrZ0oxNVdvbDh1bTZQRDRqCkYwTGRuRUlUWGdjQ2preGtmd2Vyb2RsQkFINXNqY21VQlpKd0dXZ2pwTTA9
kind: Secret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
