apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: vsphere-3par
  annotations: 
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
parameters: 
  datastoreurl: ds:///vmfs/volumes/5f3b68d3-5307add8-7fcd-c29fd5200012/
