#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@overlay/match by=overlay.subset({"kind":"KubeadmControlPlane"})
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
spec:
  kubeadmConfigSpec:
    files:
      #@overlay/append
      - content: #@ data.read("ca.crt")
        owner: root:root
        path: /usr/local/share/ca-certificates/internal-ca.pem
    preKubeadmCommands:
      #! Download and run Harbor config script
      #@overlay/append
      - update-ca-certificates
      - systemctl restart containerd
 
#@overlay/match by=overlay.subset({"kind":"KubeadmConfigTemplate"})
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfigTemplate
spec:
  template:
    spec:
      #@overlay/match missing_ok=True 
      files:
        - content: #@ data.read("ca.crt")          
          owner: root:root
          path: /usr/local/share/ca-certificates/internal-ca.pem
      preKubeadmCommands:
        #! Download and run Harbor config script
        #@overlay/append
        - update-ca-certificates
        - systemctl restart containerd
