apiVersion: v1
data:
  secretkey: Zi9aeFI1aHVQcmxTYUZPeG5rQ1habVc0VW5vNTJKbFpuWFBNQXNFT2pjMFBoSHNYeTRzOUJ6dkZmN3Vtei83ZgpvWmdtYkVZZ2cySVI5VlA5dVAvTDMyLzZSUldyclhKT3ZaNU9JNFhyTzdFYkVrOVp5QUxsUUJwMVd3Z0J1bDlZClpTb1V2NndwRk40QVR2ZEd4akZtZDlDNWRUUWJVbnA2Znp5bllFczcwTkU9
kind: Secret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
